
import { Montserrat} from "next/font/google";
import "@/app/globals.css";
import { Poppins } from "next/font/google";
export const poppins = Poppins({

  subsets: ["latin"],
  weight: ["400",'100','200','300' ,"500", "700",'600'], 
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <body >
    
      <div className="" >
       
{children}
      </div>
      
      </body>
    </html>
  );
}
