
import { Montserrat} from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/app/components/sidebar";
import { Poppins } from "next/font/google";
import { SidebarProvider } from '@/app/sidebarContext';
export const poppins = Poppins({

  subsets: ["latin"],
  weight: ["400",'100','200','300' ,"500", "700",'600'], 
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
      <body >
      <SidebarProvider>
      <div className={`${poppins.className} flex  bg-[#EDEDED] ` } >
         <Sidebar />  
{children}
      </div>
      </SidebarProvider>
      </body>
    </html>
  );
}
